version: "3"
services: 
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/var/www
        links:
            - database
        environment:
            - "DB_DATABASE=homestead"
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mysql:5.6
        volumes: 
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=homestead"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
        ports:
            - "33061:3306"
volumes:
    dbdata:
