version: "3"
services: 
    sqlserver:
        image: microsoft/mssql-server-linux
        volumes:
        - mssql-volume:/var/opt/mssql
        environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Testing123
        ports:
        - "1433:1433"
    api: 
        image: johnrob1880/omq-restapi:2.2
        environment:
            - ConnectionString=Server=sqlserver;Initial Catalog=analytics;User=sa;Password=Testing123
        ports:
            - "5101:80"
        links:
            - sqlserver
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/var/www
        links:
            - database
        environment:
            - "DB_DATABASE=omegaquant"
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mysql:5.6
        volumes: 
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=omegaquant"
            - "MYSQL_USER=omegaquant"
            - "MYSQL_PASSWORD=secret"
        ports:
            - "33061:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - database:db
        ports:
            - 8181:80
        environment:
            MYSQL_USER: omegaquant
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
volumes:
    dbdata:
    mssql-volume:
