<?php

namespace App\Constants;

class Activities
{
    const WELCOME_EMAIL_SENT = "WELCOME_EMAIL_SENT";

    const USER_LOGIN = "USER_LOGIN";

    const PAYPAL_PAYMENT_SUCCESS = "PAYPAL_PAYMENT_SUCCESS";
    const PAYPAL_PAYMENT_FAILURE = "PAYPAL_PAYMENT_FAILURE";

    const PATIENT_CREATE_SUCCESS = "PATIENT_CREATE_SUCCESS";
    const PATIENT_CREATE_FAILURE = "PATIENT_CREATE_FAILURE";

    const PATIENT_TEST_CREATE_SUCCESS = "PATIENT_TEST_CREATE_SUCCESS";
    const PATIENT_TEST_CREATE_FAILURE = "PATIENT_TEST_CREATE_FAILURE";

    const PATIENT_LINK_SUCCESS = "PATIENT_LINK_SUCCESS";
    const PATIENT_LINK_FAILURE = "PATIENT_LINK_FAILURE";

    const TEST_UPGRADE_LINK_SUCCESS = "TEST_UPGRADE_LINK_SUCCESS";
    const TEST_UPGRADE_LINK_FAILURE = "TEST_UPGRADE_LINK_FAILURE";

    const TEST_UPGRADE_COST_LINK_SUCCESS = "TEST_UPGRADE_COST_LINK_SUCCESS";
    const TEST_UPGRADE_COST_LINK_FAILURE = "TEST_UPGRADE_COST_LINK_FAILURE";

    const PAYMENT_LINK_SUCCESS = "PAYMENT_LINK_SUCCESS";
    const PAYMENT_LINK_FAILURE = "PAYMENT_LINK_FAILURE";

    const UPDATE_PATIENT_RESULT_SUCCESS = "UPDATE_PATIENT_RESULT_SUCCESS";
    const UPDATE_PATIENT_RESULT_FAILURE = "UPDATE_PATIENT_RESULT_FAILURE";

    const PREFERENCES_UPDATED = "PREFERENCES_UPDATED";
}