<?php

namespace App\Constants;

class Activities
{
    const WELCOME_EMAIL_SENT = "WELCOME_EMAIL_SENT";

    const USER_LOGIN = "USER_LOGIN";

    const PATIENT_LINK_SUCCESS = "PATIENT_LINK_SUCCESS";
    const PATIENT_LINK_FAILURE = "PATIENT_LINK_FAILURE";

    const TEST_PRICE_PAYMENT_LINK = "TEST_PRICE_PAYMENT_LINK";
    const ANALYSIS_COST_PAYMENT_LINK = "ANALYSIS_COST_PAYMENT_LINK";
}